RegisterNetEvent("SaveCommand")
AddEventHandler("SaveCommand", function()
		x, y, z = table.unpack(GetEntityCoords(GetPlayerPed(-1), true))
	    local PlayerName = GetPlayerName()
	    local PlayerHeading = GetEntityHeading(GetPlayerPed(-1))
	    TriggerServerEvent("SaveCoords", PlayerName , x , y , z, PlayerHeading)
	    local blip1 = AddBlipForCoord(GetEntityCoords(GetPlayerPed(-1), true))
	    SetBlipSprite(blip1,  1)
	    SetBlipColour(blip1,  1)
end)